Added manifests and docs for elasticsearch-kibana support
kubearmor/kubearmor-dashboards pull request #1
Opened 2023-05-29 15:07 UTC by TheRealSibasishBehera

This PR adds docs and manifests for Elasticsearch Kibana dashboards support in the relay server

2023-05-30 12:33 UTC, daemon1024 requested changes
Can you modify the README to reference respective dashboard tutorial/guides

2023-05-30 12:33 UTC, daemon1024 commented on elasticsearch-kibana/deployments/relay-deployment.yaml
> +        image: sibashi/kubearmor-relay-server:latest
```suggestion
        image: kubearmor/kubearmor-relay-server:latest
```

2023-06-07 14:59 UTC, TheRealSibasishBehera commented on elasticsearch-kibana/deployments/relay-deployment.yaml
> +        image: sibashi/kubearmor-relay-server:latest
will do that , we also have to push the image through kubearmor

2023-07-10 05:47 UTC, daemon1024 approved these changes

2023-07-10 05:47 UTC, merged